name: diffprep
channels:
  - defaults
dependencies:
  - ca-certificates=2023.05.30
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.10
  - pip=23.2.1
  - python=3.9.17
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - contourpy==1.1.0
    - cycler==0.11.0
    - fonttools==4.42.1
    - impyute==0.0.8
    - joblib==1.3.2
    - kiwisolver==1.4.4
    - matplotlib==3.6.1
    - numpy==1.23.4
    - packaging==23.1
    - pandas==1.5.0
    - pillow==10.0.0
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - pytz==2023.3
    - scikit-learn==1.3.0
    - scipy==1.9.2
    - six==1.16.0
    - threadpoolctl==3.2.0
    - torch==1.8.1
    - tqdm==4.64.1
    - typing-extensions==4.7.1